Adbase: adbase::metrics::Meters Class Reference
adbase::metrics::Meters Class Reference
#include <Meters.hpp>
Public Member Functions
Meters (const std::string moduleName, const std::string metricName, Metrics *metrics)
const std::string & getModuleName ()
const std::string & getMetricName ()
void mark ()
int64_t getCounter ()
~Meters ()
Detailed Description
Definition at line 19 of file Meters.hpp.
Constructor & Destructor Documentation
adbase::metrics::Meters::Meters (const std::string moduleName, const std::string metricName, Metrics * metrics)
Definition at line 7 of file Meters.cpp.
References adbase::metrics::Metrics::buildCounter().
adbase::metrics::Meters::~Meters ()
Definition at line 50 of file Meters.cpp.
Member Function Documentation
int64_t adbase::metrics::Meters::getCounter ()
Definition at line 40 of file Meters.cpp.
References adbase::metrics::Metrics::getCounter().
Referenced by adbase::metrics::Metrics::meter1min(), and adbase::metrics::Metrics::meter1sec().
const std::string & adbase::metrics::Meters::getMetricName ()
Definition at line 24 of file Meters.cpp.
Referenced by adbase::metrics::Metrics::getTimers(), adbase::metrics::Metrics::meter15min(), adbase::metrics::Metrics::meter1min(), adbase::metrics::Metrics::meter1sec(), and adbase::metrics::Metrics::meter5min().
const std::string & adbase::metrics::Meters::getModuleName ()
Definition at line 17 of file Meters.cpp.
Referenced by adbase::metrics::Metrics::getTimers(), adbase::metrics::Metrics::meter15min(), adbase::metrics::Metrics::meter1min(), adbase::metrics::Metrics::meter1sec(), and adbase::metrics::Metrics::meter5min().
void adbase::metrics::Meters::mark ()
Definition at line 31 of file Meters.cpp.
References adbase::metrics::Counter::add().
Referenced by adbase::metrics::Timers::setTimer(), and adbase::kafka::Consumer::threadFunc().
The documentation for this class was generated from the following files:
adbase/Metrics/Meters.hpp
adbase/Metrics/Meters.cpp