Adbase: adbase::AsyncLogging Class Reference
adbase::AsyncLogging Class Reference
adbase::Logging
#include <AsyncLogging.hpp>
Public Member Functions
AsyncLogging (const std::string &basename, size_t rollSize, int flushInterval=3)
AsyncLogging (const AsyncLogging &)=delete
void operator= (const AsyncLogging &)=delete
~AsyncLogging ()
void append (const char *logline, int len)
void start ()
void stop ()
Static Public Member Functions
static void deleteThread (std::thread *t)
Detailed Description
Definition at line 19 of file AsyncLogging.hpp.
Constructor & Destructor Documentation
adbase::AsyncLogging::AsyncLogging (const std::string & basename, size_t rollSize, int flushInterval = 3)
Definition at line 7 of file AsyncLogging.cpp.
adbase::AsyncLogging::AsyncLogging (const AsyncLogging &) delete
adbase::AsyncLogging::~AsyncLogging () inline
Definition at line 27 of file AsyncLogging.hpp.
References append(), start(), and stop().
Member Function Documentation
void adbase::AsyncLogging::append (const char * logline, int len)
Definition at line 26 of file AsyncLogging.cpp.
References adbase::LogFile::append(), adbase::LogFile::flush(), and adbase::Timestamp::now().
Referenced by adbase::http::Server::setLocationFallback(), and ~AsyncLogging().
void adbase::AsyncLogging::deleteThread (std::thread * t) static
Definition at line 123 of file AsyncLogging.cpp.
Referenced by start(), and stop().
void adbase::AsyncLogging::operator= (const AsyncLogging &) delete
void adbase::AsyncLogging::start ()
Definition at line 114 of file AsyncLogging.cpp.
References deleteThread().
Referenced by adbase::http::Server::start(), and ~AsyncLogging().
void adbase::AsyncLogging::stop () inline
Definition at line 37 of file AsyncLogging.hpp.
References deleteThread().
Referenced by ~AsyncLogging().
The documentation for this class was generated from the following files:
adbase/Logging/AsyncLogging.hpp
adbase/Logging/AsyncLogging.cpp