# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/home/zhongxiu/code/adbase_github

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/home/zhongxiu/code/adbase_github

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/home/zhongxiu/code/adbase_github/CMakeFiles /usr/home/zhongxiu/code/adbase_github/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/home/zhongxiu/code/adbase_github/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named adbase

# Build rule for target.
adbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adbase
.PHONY : adbase

# fast build rule for target.
adbase/fast:
	$(MAKE) -f adbase/CMakeFiles/adbase.dir/build.make adbase/CMakeFiles/adbase.dir/build
.PHONY : adbase/fast

#=============================================================================
# Target rules for targets named adbase_static

# Build rule for target.
adbase_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adbase_static
.PHONY : adbase_static

# fast build rule for target.
adbase_static/fast:
	$(MAKE) -f adbase/CMakeFiles/adbase_static.dir/build.make adbase/CMakeFiles/adbase_static.dir/build
.PHONY : adbase_static/fast

#=============================================================================
# Target rules for targets named buffer

# Build rule for target.
buffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buffer
.PHONY : buffer

# fast build rule for target.
buffer/fast:
	$(MAKE) -f example/CMakeFiles/buffer.dir/build.make example/CMakeFiles/buffer.dir/build
.PHONY : buffer/fast

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) -f example/CMakeFiles/config.dir/build.make example/CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named counter

# Build rule for target.
counter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 counter
.PHONY : counter

# fast build rule for target.
counter/fast:
	$(MAKE) -f example/CMakeFiles/counter.dir/build.make example/CMakeFiles/counter.dir/build
.PHONY : counter/fast

#=============================================================================
# Target rules for targets named eventloop

# Build rule for target.
eventloop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eventloop
.PHONY : eventloop

# fast build rule for target.
eventloop/fast:
	$(MAKE) -f example/CMakeFiles/eventloop.dir/build.make example/CMakeFiles/eventloop.dir/build
.PHONY : eventloop/fast

#=============================================================================
# Target rules for targets named gauges

# Build rule for target.
gauges: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gauges
.PHONY : gauges

# fast build rule for target.
gauges/fast:
	$(MAKE) -f example/CMakeFiles/gauges.dir/build.make example/CMakeFiles/gauges.dir/build
.PHONY : gauges/fast

#=============================================================================
# Target rules for targets named head

# Build rule for target.
head: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 head
.PHONY : head

# fast build rule for target.
head/fast:
	$(MAKE) -f example/CMakeFiles/head.dir/build.make example/CMakeFiles/head.dir/build
.PHONY : head/fast

#=============================================================================
# Target rules for targets named histograms

# Build rule for target.
histograms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 histograms
.PHONY : histograms

# fast build rule for target.
histograms/fast:
	$(MAKE) -f example/CMakeFiles/histograms.dir/build.make example/CMakeFiles/histograms.dir/build
.PHONY : histograms/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) -f example/CMakeFiles/http.dir/build.make example/CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named logging

# Build rule for target.
logging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logging
.PHONY : logging

# fast build rule for target.
logging/fast:
	$(MAKE) -f example/CMakeFiles/logging.dir/build.make example/CMakeFiles/logging.dir/build
.PHONY : logging/fast

#=============================================================================
# Target rules for targets named logging_out

# Build rule for target.
logging_out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logging_out
.PHONY : logging_out

# fast build rule for target.
logging_out/fast:
	$(MAKE) -f example/CMakeFiles/logging_out.dir/build.make example/CMakeFiles/logging_out.dir/build
.PHONY : logging_out/fast

#=============================================================================
# Target rules for targets named mc

# Build rule for target.
mc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mc
.PHONY : mc

# fast build rule for target.
mc/fast:
	$(MAKE) -f example/CMakeFiles/mc.dir/build.make example/CMakeFiles/mc.dir/build
.PHONY : mc/fast

#=============================================================================
# Target rules for targets named meters

# Build rule for target.
meters: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 meters
.PHONY : meters

# fast build rule for target.
meters/fast:
	$(MAKE) -f example/CMakeFiles/meters.dir/build.make example/CMakeFiles/meters.dir/build
.PHONY : meters/fast

#=============================================================================
# Target rules for targets named tcpclient

# Build rule for target.
tcpclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcpclient
.PHONY : tcpclient

# fast build rule for target.
tcpclient/fast:
	$(MAKE) -f example/CMakeFiles/tcpclient.dir/build.make example/CMakeFiles/tcpclient.dir/build
.PHONY : tcpclient/fast

#=============================================================================
# Target rules for targets named timers

# Build rule for target.
timers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timers
.PHONY : timers

# fast build rule for target.
timers/fast:
	$(MAKE) -f example/CMakeFiles/timers.dir/build.make example/CMakeFiles/timers.dir/build
.PHONY : timers/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f example/CMakeFiles/util.dir/build.make example/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named test_all

# Build rule for target.
test_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_all
.PHONY : test_all

# fast build rule for target.
test_all/fast:
	$(MAKE) -f test/CMakeFiles/test_all.dir/build.make test/CMakeFiles/test_all.dir/build
.PHONY : test_all/fast

#=============================================================================
# Target rules for targets named adbase_seed

# Build rule for target.
adbase_seed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adbase_seed
.PHONY : adbase_seed

# fast build rule for target.
adbase_seed/fast:
	$(MAKE) -f seed/CMakeFiles/adbase_seed.dir/build.make seed/CMakeFiles/adbase_seed.dir/build
.PHONY : adbase_seed/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... adbase"
	@echo "... adbase_static"
	@echo "... buffer"
	@echo "... config"
	@echo "... counter"
	@echo "... eventloop"
	@echo "... gauges"
	@echo "... head"
	@echo "... histograms"
	@echo "... http"
	@echo "... logging"
	@echo "... logging_out"
	@echo "... mc"
	@echo "... meters"
	@echo "... tcpclient"
	@echo "... timers"
	@echo "... util"
	@echo "... test_all"
	@echo "... adbase_seed"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

