Adbase: adbase::EventLoop Class Reference
adbase::EventLoop Class Reference
adbase::Net
#include <EventLoop.hpp>
Public Member Functions
EventLoop ()
~EventLoop ()
EventBasePtr & getBase ()
void start ()
void stop ()
void isStop (void *)
Detailed Description
Definition at line 17 of file EventLoop.hpp.
Constructor & Destructor Documentation
adbase::EventLoop::EventLoop ()
Definition at line 7 of file EventLoop.cpp.
adbase::EventLoop::~EventLoop ()
Definition at line 15 of file EventLoop.cpp.
Member Function Documentation
EventBasePtr & adbase::EventLoop::getBase ()
Definition at line 76 of file EventLoop.cpp.
void adbase::EventLoop::isStop (void *)
Definition at line 63 of file EventLoop.cpp.
References LOG_ERROR.
Referenced by start().
void adbase::EventLoop::start ()
Definition at line 21 of file EventLoop.cpp.
References isStop(), and adbase::Timer::runEvery().
void adbase::EventLoop::stop ()
Definition at line 38 of file EventLoop.cpp.
References LOG_ERROR.
The documentation for this class was generated from the following files:
adbase/Net/EventLoop.hpp
adbase/Net/EventLoop.cpp