Adbase: adbase::detail::File Class Reference
adbase::detail::File Class Reference
Public Member Functions
File (const char *file)
~File ()
bool valid () const
std::string readBytes (int n)
int32_t readInt32 ()
uint8_t readUInt8 ()
Detailed Description
Definition at line 80 of file TimeZone.cpp.
Constructor & Destructor Documentation
adbase::detail::File::File (const char * file) inline
Definition at line 82 of file TimeZone.cpp.
adbase::detail::File::~File () inline
Definition at line 86 of file TimeZone.cpp.
Member Function Documentation
std::string adbase::detail::File::readBytes (int n) inline
Definition at line 94 of file TimeZone.cpp.
Referenced by adbase::detail::readTimeZoneFile().
int32_t adbase::detail::File::readInt32 () inline
Definition at line 102 of file TimeZone.cpp.
References adbase::networkToHost32().
Referenced by adbase::detail::readTimeZoneFile().
uint8_t adbase::detail::File::readUInt8 () inline
Definition at line 110 of file TimeZone.cpp.
Referenced by adbase::detail::readTimeZoneFile().
bool adbase::detail::File::valid () const inline
Definition at line 92 of file TimeZone.cpp.
Referenced by adbase::detail::readTimeZoneFile().
The documentation for this class was generated from the following file:
adbase/Utility/TimeZone.cpp