Adbase: adbase::http::Response Class Reference
adbase::http::Response Class Reference
#include <Response.hpp>
Public Member Functions
Response (evhttp_request *req)
int setHeader (const std::string &key, const std::string &value, bool isReplace=true)
设置 header 信息
int addHeader (const std::string &key, const std::string &value)
添加 header 信息
void setContent (const std::string &data)
设置响应 body 信息
void appendContent (const std::string &data, bool isAfter=true)
追加响应 body 信息
void sendReply (const std::string &reason="OK", int code=HTTP_OK, const std::string &data="")
发送响应信息
int getCode ()
获取状态码
size_t getBodySize ()
获取响应数据大小
virtual ~Response ()
Detailed Description
Definition at line 22 of file Response.hpp.
Constructor & Destructor Documentation
adbase::http::Response::Response (evhttp_request * req)
Definition at line 9 of file Response.cpp.
virtual adbase::http::Response::~Response () inline virtual
Definition at line 47 of file Response.hpp.
Member Function Documentation
int adbase::http::Response::addHeader (const std::string & key, const std::string & value)
添加 header 信息
Definition at line 34 of file Response.cpp.
void adbase::http::Response::appendContent (const std::string & data, bool isAfter = true)
追加响应 body 信息
Definition at line 53 of file Response.cpp.
size_t adbase::http::Response::getBodySize () inline
获取响应数据大小
Definition at line 45 of file Response.hpp.
Referenced by adbase::http::Server::onRequestCallback().
int adbase::http::Response::getCode () inline
获取状态码
Definition at line 42 of file Response.hpp.
Referenced by adbase::http::Server::onRequestCallback().
void adbase::http::Response::sendReply (const std::string & reason = "OK", int code = HTTP_OK, const std::string & data = "")
发送响应信息
Definition at line 65 of file Response.cpp.
References LOG_INFO.
Referenced by adbase::http::Server::onRequestCallback().
void adbase::http::Response::setContent (const std::string & data)
设置响应 body 信息
Definition at line 42 of file Response.cpp.
int adbase::http::Response::setHeader (const std::string & key, const std::string & value, bool isReplace = true)
设置 header 信息
Definition at line 17 of file Response.cpp.
The documentation for this class was generated from the following files:
adbase/Http/Response.hpp
adbase/Http/Response.cpp