Adbase: adbase::kafka::Consumer Class Reference
adbase::kafka::Consumer Class Reference
#include <Consumer.hpp>
Public Member Functions
Consumer (const std::string &topicName, const std::string &groupId, const std::string &brokerList)
~Consumer ()
void start ()
void stop ()
void threadFunc (void *data)
const std::string & getTopicName ()
const std::string & getGroupId ()
void setMessageHandler (const ConsumerMessageCallback &messageHandler)
void setStatCallback (const ConsumerStatCallback &statHandler)
void statCallback (Consumer *consumer, const std::string &stat)
void setKafkaCommitInterval (const std::string &commitInterval)
void setKafkaQueuedMinMessages (const std::string &queueMinMessages)
void setKafkaQueuedMaxSize (const std::string &queueMaxSize)
void setKafkaStatInterval (const std::string &statInterval)
void setKafkaDebug (const std::string &debug)
void setConsumeTimeout (int consumerTimeout)
void setOffsetStorePath (const std::string &path)
void setOffsetStoreMethod (const std::string &method)
void setOffsetReset (const std::string &offsetReset)
void setIsNewConsumer (bool isNewConsumer)
Static Public Member Functions
static void deleteThread (std::thread *t)
static void logger (const rd_kafka_t *rk, int level, const char *fac, const char *buf)
static void rebalanceCallback (rd_kafka_t *rk, rd_kafka_resp_err_t err, rd_kafka_topic_partition_list_t *partitions, void *opaque)
static int statsCallback (rd_kafka_t *rk, char *json, size_t jsonLen, void *opaque)
Detailed Description
Definition at line 27 of file Consumer.hpp.
Constructor & Destructor Documentation
adbase::kafka::Consumer::Consumer (const std::string & topicName, const std::string & groupId, const std::string & brokerList)
Definition at line 10 of file Consumer.cpp.
adbase::kafka::Consumer::~Consumer ()
Definition at line 27 of file Consumer.cpp.
Member Function Documentation
void adbase::kafka::Consumer::deleteThread (std::thread * t) static
Definition at line 260 of file Consumer.cpp.
References LOG_ERROR.
Referenced by start().
const std::string& adbase::kafka::Consumer::getGroupId () inline
Definition at line 45 of file Consumer.hpp.
const std::string& adbase::kafka::Consumer::getTopicName () inline
Definition at line 41 of file Consumer.hpp.
void adbase::kafka::Consumer::logger (const rd_kafka_t * rk, int level, const char * fac, const char * buf) static
Definition at line 269 of file Consumer.cpp.
Referenced by threadFunc().
void adbase::kafka::Consumer::rebalanceCallback (rd_kafka_t * rk, rd_kafka_resp_err_t err, rd_kafka_topic_partition_list_t * partitions, void * opaque) static
Definition at line 308 of file Consumer.cpp.
References LOG_ERROR, and LOG_INFO.
Referenced by threadFunc().
void adbase::kafka::Consumer::setConsumeTimeout (int consumerTimeout) inline
Definition at line 78 of file Consumer.hpp.
void adbase::kafka::Consumer::setIsNewConsumer (bool isNewConsumer) inline
Definition at line 94 of file Consumer.hpp.
void adbase::kafka::Consumer::setKafkaCommitInterval (const std::string & commitInterval) inline
Definition at line 58 of file Consumer.hpp.
void adbase::kafka::Consumer::setKafkaDebug (const std::string & debug) inline
Definition at line 74 of file Consumer.hpp.
void adbase::kafka::Consumer::setKafkaQueuedMaxSize (const std::string & queueMaxSize) inline
Definition at line 66 of file Consumer.hpp.
void adbase::kafka::Consumer::setKafkaQueuedMinMessages (const std::string & queueMinMessages) inline
Definition at line 62 of file Consumer.hpp.
void adbase::kafka::Consumer::setKafkaStatInterval (const std::string & statInterval) inline
Definition at line 70 of file Consumer.hpp.
void adbase::kafka::Consumer::setMessageHandler (const ConsumerMessageCallback & messageHandler) inline
Definition at line 49 of file Consumer.hpp.
void adbase::kafka::Consumer::setOffsetReset (const std::string & offsetReset) inline
Definition at line 90 of file Consumer.hpp.
void adbase::kafka::Consumer::setOffsetStoreMethod (const std::string & method) inline
Definition at line 86 of file Consumer.hpp.
void adbase::kafka::Consumer::setOffsetStorePath (const std::string & path) inline
Definition at line 82 of file Consumer.hpp.
void adbase::kafka::Consumer::setStatCallback (const ConsumerStatCallback & statHandler) inline
Definition at line 53 of file Consumer.hpp.
References statCallback().
void adbase::kafka::Consumer::start ()
Definition at line 45 of file Consumer.cpp.
References deleteThread(), and threadFunc().
void adbase::kafka::Consumer::statCallback (Consumer * consumer, const std::string & stat)
Definition at line 290 of file Consumer.cpp.
Referenced by setStatCallback(), and statsCallback().
int adbase::kafka::Consumer::statsCallback (rd_kafka_t * rk, char * json, size_t jsonLen, void * opaque) static
Definition at line 297 of file Consumer.cpp.
References statCallback().
Referenced by threadFunc().
void adbase::kafka::Consumer::stop ()
Definition at line 33 of file Consumer.cpp.
References LOG_ERROR.
void adbase::kafka::Consumer::threadFunc (void * data)
Definition at line 58 of file Consumer.cpp.
References adbase::Buffer::append(), adbase::metrics::Metrics::buildMeters(), LOG_ERROR, LOG_INFO, LOG_TRACE, logger(), adbase::metrics::Meters::mark(), rebalanceCallback(), adbase::Buffer::retrieveAll(), and statsCallback().
Referenced by start().
The documentation for this class was generated from the following files:
adbase/Kafka/Consumer.hpp
adbase/Kafka/Consumer.cpp