Adbase: adbase::metrics::Timers Class Reference
adbase::metrics::Timers Class Reference
#include <Timers.hpp>
Public Member Functions
Timers (const std::string moduleName, const std::string metricName, Metrics *metrics, uint32_t interval)
const std::string & getModuleName ()
const std::string & getMetricName ()
void start ()
void setTimer (double time)
Meters * getMeters ()
Histograms * getHistograms ()
~Timers ()
Detailed Description
Definition at line 20 of file Timers.hpp.
Constructor & Destructor Documentation
adbase::metrics::Timers::Timers (const std::string moduleName, const std::string metricName, Metrics * metrics, uint32_t interval)
Definition at line 8 of file Timers.cpp.
References adbase::metrics::Metrics::buildHistograms(), and adbase::metrics::Metrics::buildMeters().
adbase::metrics::Timers::~Timers ()
Definition at line 60 of file Timers.cpp.
Member Function Documentation
Histograms * adbase::metrics::Timers::getHistograms ()
Definition at line 46 of file Timers.cpp.
Meters * adbase::metrics::Timers::getMeters ()
Definition at line 53 of file Timers.cpp.
Referenced by adbase::metrics::Metrics::getTimers().
const std::string & adbase::metrics::Timers::getMetricName ()
Definition at line 27 of file Timers.cpp.
const std::string & adbase::metrics::Timers::getModuleName ()
Definition at line 20 of file Timers.cpp.
void adbase::metrics::Timers::setTimer (double time)
Definition at line 34 of file Timers.cpp.
References adbase::metrics::Meters::mark(), and adbase::metrics::Histograms::update().
Referenced by adbase::http::Server::onRequestCallback().
void adbase::metrics::Timers::start ()
The documentation for this class was generated from the following files:
adbase/Metrics/Timers.hpp
adbase/Metrics/Timers.cpp