Adbase: adbase::metrics::Counter Class Reference
adbase::metrics::Counter Class Reference
#include <Counter.hpp>
Public Member Functions
Counter (const std::string moduleName, const std::string metricName, Metrics *metrics, adbase::Queue< DataItem > *queue)
const std::string & getModuleName ()
const std::string & getMetricName ()
void add (int64_t val=1)
void dec (int64_t val=1)
~Counter ()
Detailed Description
Definition at line 19 of file Counter.hpp.
Constructor & Destructor Documentation
adbase::metrics::Counter::Counter (const std::string moduleName, const std::string metricName, Metrics * metrics, adbase::Queue< DataItem > * queue)
Definition at line 7 of file Counter.cpp.
adbase::metrics::Counter::~Counter ()
Definition at line 54 of file Counter.cpp.
Member Function Documentation
void adbase::metrics::Counter::add (int64_t val = 1)
Definition at line 32 of file Counter.cpp.
References adbase::metrics::dataItem::context, adbase::metrics::METRICS_COUNTER, adbase::metrics::dataItem::type, and adbase::metrics::dataItem::val.
Referenced by adbase::metrics::Meters::mark().
void adbase::metrics::Counter::dec (int64_t val = 1)
Definition at line 43 of file Counter.cpp.
References adbase::metrics::dataItem::context, adbase::metrics::METRICS_COUNTER, adbase::metrics::dataItem::type, and adbase::metrics::dataItem::val.
const std::string & adbase::metrics::Counter::getMetricName ()
Definition at line 25 of file Counter.cpp.
Referenced by adbase::metrics::Metrics::setCounter().
const std::string & adbase::metrics::Counter::getModuleName ()
Definition at line 18 of file Counter.cpp.
Referenced by adbase::metrics::Metrics::setCounter().
The documentation for this class was generated from the following files:
adbase/Metrics/Counter.hpp
adbase/Metrics/Counter.cpp