Adbase: adbase::metrics::Histograms Class Reference
adbase::metrics::Histograms Class Reference
#include <Histograms.hpp>
Public Member Functions
Histograms (const std::string moduleName, const std::string metricName, uint32_t interval, Metrics *metrics, adbase::Queue< DataItem > *queue)
uint32_t interval ()
const std::string & getModuleName ()
const std::string & getMetricName ()
void update (double val)
~Histograms ()
Detailed Description
Definition at line 19 of file Histograms.hpp.
Constructor & Destructor Documentation
adbase::metrics::Histograms::Histograms (const std::string moduleName, const std::string metricName, uint32_t interval, Metrics * metrics, adbase::Queue< DataItem > * queue)
Definition at line 7 of file Histograms.cpp.
adbase::metrics::Histograms::~Histograms ()
Definition at line 51 of file Histograms.cpp.
Member Function Documentation
const std::string & adbase::metrics::Histograms::getMetricName ()
Definition at line 26 of file Histograms.cpp.
Referenced by adbase::metrics::Metrics::histograms(), and adbase::metrics::Metrics::setHistograms().
const std::string & adbase::metrics::Histograms::getModuleName ()
Definition at line 19 of file Histograms.cpp.
Referenced by adbase::metrics::Metrics::histograms(), and adbase::metrics::Metrics::setHistograms().
uint32_t adbase::metrics::Histograms::interval ()
Definition at line 33 of file Histograms.cpp.
void adbase::metrics::Histograms::update (double val)
Definition at line 40 of file Histograms.cpp.
References adbase::metrics::dataItem::context, adbase::metrics::METRICS_HISTOGRAMS, adbase::metrics::dataItem::type, and adbase::metrics::dataItem::val.
Referenced by adbase::metrics::Timers::setTimer().
The documentation for this class was generated from the following files:
adbase/Metrics/Histograms.hpp
adbase/Metrics/Histograms.cpp