cmake_minimum_required(VERSION 2.6)
//@IF @grpc
FIND_PACKAGE(Protobuf REQUIRED)
MESSAGE(STATUS "Using protobuf ${protobuf_VERSION}")

FIND_PACKAGE(GRPC REQUIRED)
MESSAGE(STATUS "Using gRPC ${gRPC_VERSION}")

SET(PROTO_SRC_DIR ${CMAKE_CURRENT_BINARY_DIR}/proto-src)
FILE(MAKE_DIRECTORY ${PROTO_SRC_DIR})
INCLUDE_DIRECTORIES(${PROTO_SRC_DIR})

PROTOBUF_GENERATE_CPP(PROTO_SRCS PROTO_HDRS ${PROTO_SRC_DIR} ${PROTOS})
GRPC_GENERATE_CPP(GRPC_SRCS GRPC_HDRS ${PROTO_SRC_DIR} ${PROTOS})
MESSAGE(${GRPC_HDRS})
//@ENDIF
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/src)
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/src/thridpart)
LINK_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})

SET(CMAKE_SOURCE_DIR .)
SET(CMAKE_MODULE_PATH ${CMAKE_ROOT}/Modules ${CMAKE_SOURCE_DIR}/cmake/Modules
                ${PROJECT_SOURCE_DIR}/Modules)

configure_file (
	"${PROJECT_SOURCE_DIR}/src/Version.hpp.in"	
	"${PROJECT_SOURCE_DIR}/src/Version.hpp"	
)

SET(@ADINF_PROJECT_NAME|upper@_SRC @ADINF_PROJECT_NAME@.cpp
	BootStrap.cpp	
	App.cpp	
	//@IF @adserver
	AdServer.cpp
	Http.cpp
	Http/HttpInterface.cpp
	Http/Server.cpp
	//@FOR @http_controllers
	Http/@REPLACE0@.cpp
	//@ENDFOR
	McProcessor.cpp
	//@ENDIF
	//@IF @kafkac || @kafkap
	Aims.cpp
	//@ENDIF
	//@IF @kafkac
	Aims/Kafka/Consumer.cpp
	//@ENDIF
	//@IF @kafkap
	Aims/Kafka/Producer.cpp
	//@ENDIF
	Timer.cpp
	//@IF @grpc
	Grpc.cpp
	Grpc/ServerServiceImpl.cpp
	${PROTO_SRCS}
	${GRPC_SRCS}
	//@ENDIF
)
ADD_EXECUTABLE(@ADINF_PROJECT_NAME@ ${@ADINF_PROJECT_NAME|upper@_SRC})

# adbase
FIND_PACKAGE( libadbase REQUIRED)
MARK_AS_ADVANCED(
LIBADBASE_INCLUDE_DIR
LIBADBASE_LIBRARIES
)
IF (LIBADBASE_INCLUDE_DIR AND LIBADBASE_LIBRARIES)
    MESSAGE(STATUS "Found libadbase libraries")
    INCLUDE_DIRECTORIES(${LIBADBASE_INCLUDE_DIR})
    MESSAGE( ${LIBADBASE_LIBRARIES} )
    TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ ${LIBADBASE_LIBRARIES} )
ELSE (LIBADBASE_INCLUDE_DIR AND LIBADBASE_LIBRARIES)
    MESSAGE(FATAL_ERROR "Failed to find libadbase libraries")
ENDIF (LIBADBASE_INCLUDE_DIR AND LIBADBASE_LIBRARIES)

//@IF @kafkac || @kafkap
# adbase_kafka
FIND_PACKAGE( libadbase_kafka REQUIRED)
MARK_AS_ADVANCED(
LIBADBASE_KAFKA_INCLUDE_DIR
LIBADBASE_KAFKA_LIBRARIES
)
IF (LIBADBASE_KAFKA_INCLUDE_DIR AND LIBADBASE_KAFKA_LIBRARIES)
    MESSAGE(STATUS "Found libadbase_kafka libraries")
    INCLUDE_DIRECTORIES(${LIBADBASE_KAFKA_INCLUDE_DIR})
    MESSAGE( ${LIBADBASE_KAFKA_LIBRARIES} )
    TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ ${LIBADBASE_KAFKA_LIBRARIES} )
ELSE (LIBADBASE_KAFKA_INCLUDE_DIR AND LIBADBASE_KAFKA_LIBRARIES)
    MESSAGE(FATAL_ERROR "Failed to find libadbase_kafka libraries")
ENDIF (LIBADBASE_KAFKA_INCLUDE_DIR AND LIBADBASE_KAFKA_LIBRARIES)


# rdkafka++
FIND_PACKAGE( librdkafka REQUIRED)
MARK_AS_ADVANCED(
        LIBRDKAFKA_INCLUDE_DIR
        LIBRDKAFKA_LIBRARIES
)
IF (LIBRDKAFKA_INCLUDE_DIR AND LIBRDKAFKA_LIBRARIES)
        MESSAGE(STATUS "Found librdkafka libraries")
        INCLUDE_DIRECTORIES(${LIBRDKAFKA_INCLUDE_DIR})
        MESSAGE( ${LIBRDKAFKA_LIBRARIES} )
        TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ ${LIBRDKAFKA_CPP_LIBRARIES} )
        TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ ${LIBRDKAFKA_LIBRARIES} )
ELSE (LIBRDKAFKA_INCLUDE_DIR AND LIBRDKAFKA_LIBRARIES)
        MESSAGE(FATAL_ERROR "Failed to find librdkafka libraries")
ENDIF (LIBRDKAFKA_INCLUDE_DIR AND LIBRDKAFKA_LIBRARIES)

//@ENDIF

TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ libevent.a rt libz.a dl)

//@IF @grpc
TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ grpc++_reflection libgrpc++_unsecure.a libgrpc++.a libgrpc.a libz.a libprotobuf.a ssl crypto)
//@ENDIF


# pthread
FIND_PACKAGE( libpthread REQUIRED)
MARK_AS_ADVANCED(
LIBPTHREAD_INCLUDE_DIR
LIBPTHREAD_LIBRARIES
)
IF (LIBPTHREAD_INCLUDE_DIR AND LIBPTHREAD_LIBRARIES)
    MESSAGE(STATUS "Found libpthread libraries")
    INCLUDE_DIRECTORIES(${LIBPTHREAD_INCLUDE_DIR})
    MESSAGE( ${LIBPTHREAD_LIBRARIES} )
    TARGET_LINK_LIBRARIES(@ADINF_PROJECT_NAME@ ${LIBPTHREAD_LIBRARIES} )
ELSE (LIBPTHREAD_INCLUDE_DIR AND LIBPTHREAD_LIBRARIES)
    MESSAGE(FATAL_ERROR "Failed to find libpthread libraries")
ENDIF (LIBPTHREAD_INCLUDE_DIR AND LIBPTHREAD_LIBRARIES)

INSTALL(TARGETS @ADINF_PROJECT_NAME@ RUNTIME DESTINATION bin)
