Adbase: adbase::sockets Namespace Reference
adbase::sockets Namespace Reference
adbase::Net
Functions
void setNonBlock (int sockfd)
const struct sockaddr * sockaddrCast (const struct sockaddr_in *addr)
struct sockaddr * sockaddrCast (struct sockaddr_in *addr)
const struct sockaddr_in * sockaddrInCast (const struct sockaddr *addr)
struct sockaddr_in * sockaddrInCast (struct sockaddr *addr)
int createNonblockingOrDie ()
void bindOrDie (int sockfd, const struct sockaddr_in &addr)
void listenOrDie (int sockfd)
int accept (int sockfd, struct sockaddr_in *addr)
int connect (int sockfd, const struct sockaddr_in &addr)
void close (int sockfd)
void shutdownWrite (int sockfd)
void toIpPort (char *buf, size_t size, const struct sockaddr_in &addr)
void toIp (char *buf, size_t size, const struct sockaddr_in &addr)
void fromIpPort (const char *ip, uint16_t port, struct sockaddr_in *addr)
int getSocketError (int sockfd)
struct sockaddr_in getLocalAddr (int sockfd)
struct sockaddr_in getPeerAddr (int sockfd)
bool isSelfConnect (int sockfd)
Function Documentation
int adbase::sockets::accept (int sockfd, struct sockaddr_in * addr)
Definition at line 111 of file SocketsOps.cpp.
References LOG_FATAL, LOG_SYSERR, setNonBlockAndCloseOnExec(), and sockaddrCast().
Referenced by adbase::Socket::accept(), and adbase::detail::acceptHandler().
void adbase::sockets::bindOrDie (int sockfd, const struct sockaddr_in & addr)
Definition at line 91 of file SocketsOps.cpp.
References LOG_SYSFATAL, and sockaddrCast().
Referenced by adbase::Socket::bindAddress().
void adbase::sockets::close (int sockfd)
Definition at line 160 of file SocketsOps.cpp.
References LOG_SYSERR.
Referenced by adbase::Connector::handleError(), adbase::Connector::handleWrite(), adbase::ifconfig(), adbase::Acceptor::init(), adbase::Connector::restart(), adbase::ReadSmallFile::~ReadSmallFile(), and adbase::Socket::~Socket().
int adbase::sockets::connect (int sockfd, const struct sockaddr_in & addr)
Definition at line 153 of file SocketsOps.cpp.
References sockaddrCast().
Referenced by adbase::Connector::restart(), and adbase::Connector::serverAddress().
int adbase::sockets::createNonblockingOrDie ()
Definition at line 70 of file SocketsOps.cpp.
References LOG_SYSFATAL, and setNonBlockAndCloseOnExec().
Referenced by adbase::Connector::restart().
void adbase::sockets::fromIpPort (const char * ip, uint16_t port, struct sockaddr_in * addr)
Definition at line 200 of file SocketsOps.cpp.
References adbase::hostToNetwork16(), and LOG_SYSERR.
Referenced by adbase::InetAddress::InetAddress().
struct sockaddr_in adbase::sockets::getLocalAddr (int sockfd)
Definition at line 226 of file SocketsOps.cpp.
References LOG_SYSERR, and sockaddrCast().
Referenced by isSelfConnect(), and adbase::TcpClient::stop().
struct sockaddr_in adbase::sockets::getPeerAddr (int sockfd)
Definition at line 240 of file SocketsOps.cpp.
References LOG_SYSERR, and sockaddrCast().
Referenced by isSelfConnect(), and adbase::TcpClient::stop().
int adbase::sockets::getSocketError (int sockfd)
Definition at line 212 of file SocketsOps.cpp.
Referenced by adbase::Connector::handleError(), and adbase::Connector::handleWrite().
bool adbase::sockets::isSelfConnect (int sockfd)
Definition at line 254 of file SocketsOps.cpp.
References getLocalAddr(), and getPeerAddr().
Referenced by adbase::Connector::handleWrite().
void adbase::sockets::listenOrDie (int sockfd)
Definition at line 101 of file SocketsOps.cpp.
References LOG_SYSFATAL.
Referenced by adbase::Socket::listen().
void adbase::sockets::setNonBlock (int sockfd)
Definition at line 33 of file SocketsOps.cpp.
void adbase::sockets::shutdownWrite (int sockfd)
Definition at line 169 of file SocketsOps.cpp.
References LOG_SYSERR.
Referenced by adbase::Socket::shutdownWrite().
const struct sockaddr * adbase::sockets::sockaddrCast (const struct sockaddr_in * addr)
Definition at line 42 of file SocketsOps.cpp.
Referenced by accept(), bindOrDie(), connect(), getLocalAddr(), and getPeerAddr().
struct sockaddr * adbase::sockets::sockaddrCast (struct sockaddr_in * addr)
Definition at line 49 of file SocketsOps.cpp.
const struct sockaddr_in * adbase::sockets::sockaddrInCast (const struct sockaddr * addr)
Definition at line 56 of file SocketsOps.cpp.
struct sockaddr_in * adbase::sockets::sockaddrInCast (struct sockaddr * addr)
Definition at line 63 of file SocketsOps.cpp.
void adbase::sockets::toIp (char * buf, size_t size, const struct sockaddr_in & addr)
Definition at line 191 of file SocketsOps.cpp.
Referenced by adbase::InetAddress::toIp().
void adbase::sockets::toIpPort (char * buf, size_t size, const struct sockaddr_in & addr)
Definition at line 178 of file SocketsOps.cpp.
References adbase::networkToHost16().
Referenced by adbase::InetAddress::toIpPort().