Adbase: adbase::LogFile Class Reference
adbase::LogFile Class Reference
adbase::Logging
#include <LogFile.hpp>
Public Member Functions
LogFile (const std::string &basename, size_t rollSize, bool threadSafe=true, int flushInterval=3, int checkEveryN=1024)
~LogFile ()
void append (const char *logline, int len)
void flush ()
bool rollFile ()
Detailed Description
Definition at line 20 of file LogFile.hpp.
Constructor & Destructor Documentation
adbase::LogFile::LogFile (const std::string & basename, size_t rollSize, bool threadSafe = true, int flushInterval = 3, int checkEveryN = 1024)
Definition at line 7 of file LogFile.cpp.
References rollFile().
adbase::LogFile::~LogFile ()
Definition at line 36 of file LogFile.cpp.
Member Function Documentation
void adbase::LogFile::append (const char * logline, int len)
Definition at line 42 of file LogFile.cpp.
Referenced by adbase::AsyncLogging::append().
void adbase::LogFile::flush ()
Definition at line 52 of file LogFile.cpp.
References rollFile().
Referenced by adbase::AsyncLogging::append().
bool adbase::LogFile::rollFile ()
Definition at line 86 of file LogFile.cpp.
References adbase::hostname(), and adbase::pid().
Referenced by flush(), and LogFile().
The documentation for this class was generated from the following files:
adbase/Logging/LogFile.hpp
adbase/Logging/LogFile.cpp