Adbase: adbase::detail::FixedBuffer< SIZE > Class Template Reference
adbase::detail::FixedBuffer< SIZE > Class Template Reference
#include <LogStream.hpp>
Public Member Functions
FixedBuffer ()
~FixedBuffer ()
void append (const char *buf, size_t len)
const char * data () const
int length () const
char * current ()
int avail () const
void add (size_t len)
void reset ()
void bzero ()
const char * debugString ()
void setCookie (void(*cookie)())
std::string toString () const
Detailed Description
template<int SIZE>
class adbase::detail::FixedBuffer< SIZE >
Definition at line 25 of file LogStream.hpp.
Constructor & Destructor Documentation
template<int SIZE> adbase::detail::FixedBuffer< SIZE >::FixedBuffer () inline
Definition at line 27 of file LogStream.hpp.
template<int SIZE> adbase::detail::FixedBuffer< SIZE >::~FixedBuffer () inline
Definition at line 31 of file LogStream.hpp.
Member Function Documentation
template<int SIZE> void adbase::detail::FixedBuffer< SIZE >::add (size_t len) inline
Definition at line 62 of file LogStream.hpp.
template<int SIZE> void adbase::detail::FixedBuffer< SIZE >::append (const char * buf, size_t len) inline
Definition at line 35 of file LogStream.hpp.
template<int SIZE> int adbase::detail::FixedBuffer< SIZE >::avail () const inline
Definition at line 58 of file LogStream.hpp.
Referenced by adbase::detail::FixedBuffer< detail::kSmallBuffer >::append().
template<int SIZE> void adbase::detail::FixedBuffer< SIZE >::bzero () inline
Definition at line 70 of file LogStream.hpp.
Referenced by adbase::detail::FixedBuffer< detail::kSmallBuffer >::bzero().
template<int SIZE> char* adbase::detail::FixedBuffer< SIZE >::current () inline
Definition at line 54 of file LogStream.hpp.
template<int SIZE> const char* adbase::detail::FixedBuffer< SIZE >::data () const inline
Definition at line 46 of file LogStream.hpp.
Referenced by adbase::Logger::~Logger().
template<int SIZE> const char * adbase::FixedBuffer::debugString ()
Definition at line 65 of file LogStream.cpp.
References adbase::detail::convert().
Referenced by adbase::detail::FixedBuffer< detail::kSmallBuffer >::bzero().
template<int SIZE> int adbase::detail::FixedBuffer< SIZE >::length () const inline
Definition at line 50 of file LogStream.hpp.
Referenced by adbase::detail::FixedBuffer< detail::kSmallBuffer >::append(), adbase::detail::FixedBuffer< detail::kSmallBuffer >::toString(), and adbase::Logger::~Logger().
template<int SIZE> void adbase::detail::FixedBuffer< SIZE >::reset () inline
Definition at line 66 of file LogStream.hpp.
template<int SIZE> void adbase::detail::FixedBuffer< SIZE >::setCookie (void(*)() cookie) inline
Definition at line 76 of file LogStream.hpp.
Referenced by adbase::detail::FixedBuffer< detail::kSmallBuffer >::FixedBuffer(), and adbase::detail::FixedBuffer< detail::kSmallBuffer >::~FixedBuffer().
template<int SIZE> std::string adbase::detail::FixedBuffer< SIZE >::toString () const inline
Definition at line 80 of file LogStream.hpp.
Referenced by adbase::LogStream::operator<<().
The documentation for this class was generated from the following files:
adbase/Logging/LogStream.hpp
adbase/Logging/LogStream.cpp