Adbase: adbase::Timer Class Reference
adbase::Timer Class Reference
adbase::Net
#include <Timer.hpp>
Public Member Functions
Timer (EventBasePtr &base)
~Timer ()
uint64_t runEvery (int interval, const TimerCallback &cb, void *context)
uint64_t runAfter (int interval, const TimerCallback &cb, void *context)
void cancel (uint64_t timerId)
void stop ()
Detailed Description
Definition at line 48 of file Timer.hpp.
Constructor & Destructor Documentation
adbase::Timer::Timer (EventBasePtr & base)
Definition at line 18 of file Timer.cpp.
adbase::Timer::~Timer ()
Definition at line 26 of file Timer.cpp.
Member Function Documentation
void adbase::Timer::cancel (uint64_t timerId)
Definition at line 56 of file Timer.cpp.
Referenced by runAfter(), and runEvery().
uint64_t adbase::Timer::runAfter (int interval, const TimerCallback & cb, void * context)
Definition at line 32 of file Timer.cpp.
References cancel().
Referenced by adbase::Connector::handleError().
uint64_t adbase::Timer::runEvery (int interval, const TimerCallback & cb, void * context)
Definition at line 44 of file Timer.cpp.
References cancel().
Referenced by adbase::metrics::Metrics::createGauges(), adbase::metrics::Metrics::createHistograms(), adbase::metrics::Metrics::createMeters(), and adbase::EventLoop::start().
void adbase::Timer::stop ()
Definition at line 65 of file Timer.cpp.
The documentation for this class was generated from the following files:
adbase/Net/Timer.hpp
adbase/Net/Timer.cpp