Adbase: adbase::ReadSmallFile Class Reference
adbase::ReadSmallFile Class Reference
adbase::Utility
#include <FileSystem.hpp>
Public Member Functions
ReadSmallFile (std::string filename)
~ReadSmallFile ()
template<typename S >
int readToString (int maxSize, S *context, int64_t *fileSize, int64_t *modifyTime, int64_t *createTime)
int readToBuffer (int *size)
const char * buffer () const
Static Public Attributes
static const int kBufferSize = 64 * 1024
Detailed Description
Definition at line 23 of file FileSystem.hpp.
Constructor & Destructor Documentation
adbase::ReadSmallFile::ReadSmallFile (std::string filename)
Definition at line 63 of file FileSystem.cpp.
adbase::ReadSmallFile::~ReadSmallFile ()
Definition at line 78 of file FileSystem.cpp.
References adbase::sockets::close().
Member Function Documentation
const char* adbase::ReadSmallFile::buffer () const inline
Definition at line 38 of file FileSystem.hpp.
int adbase::ReadSmallFile::readToBuffer (int * size)
Definition at line 141 of file FileSystem.cpp.
References adbase::readFile(), and readToString().
template<typename S > template int adbase::ReadSmallFile::readToString (int maxSize, S * context, int64_t * fileSize, int64_t * modifyTime, int64_t * createTime)
Definition at line 89 of file FileSystem.cpp.
Referenced by adbase::readFile(), and readToBuffer().
Member Data Documentation
const int adbase::ReadSmallFile::kBufferSize = 64 * 1024 static
Definition at line 42 of file FileSystem.hpp.
The documentation for this class was generated from the following files:
adbase/Utility/FileSystem.hpp
adbase/Utility/FileSystem.cpp