Adbase: adbase::LogStream Class Reference
adbase::LogStream Class Reference
adbase::Logging
#include <LogStream.hpp>
Public Types
typedef LogStream self
typedef detail::FixedBuffer< detail::kSmallBuffer > Buffer
Public Member Functions
self & operator<< (bool v)
self & operator<< (short)
self & operator<< (unsigned short)
self & operator<< (int)
self & operator<< (unsigned int)
self & operator<< (long)
self & operator<< (unsigned long)
self & operator<< (long long)
self & operator<< (unsigned long long)
self & operator<< (const void *)
self & operator<< (float v)
self & operator<< (double)
self & operator<< (char v)
self & operator<< (const char *str)
self & operator<< (const unsigned char *str)
self & operator<< (const std::string &v)
self & operator<< (const Buffer &v)
void append (const char *data, int len)
const Buffer & buffer () const
void resetBuffer ()
Detailed Description
Definition at line 103 of file LogStream.hpp.
Member Typedef Documentation
typedef detail::FixedBuffer<detail::kSmallBuffer> adbase::LogStream::Buffer
Definition at line 106 of file LogStream.hpp.
typedef LogStream adbase::LogStream::self
Definition at line 105 of file LogStream.hpp.
Member Function Documentation
void adbase::LogStream::append (const char * data, int len) inline
Definition at line 158 of file LogStream.hpp.
Referenced by adbase::operator<<(), and operator<<().
const Buffer& adbase::LogStream::buffer () const inline
Definition at line 162 of file LogStream.hpp.
self& adbase::LogStream::operator<< (bool v) inline
Definition at line 107 of file LogStream.hpp.
References append(), and adbase::operator<<().
LogStream & adbase::LogStream::operator<< (short v)
Definition at line 96 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (unsigned short v)
Definition at line 101 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (int v)
Definition at line 106 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (unsigned int v)
Definition at line 111 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (long v)
Definition at line 116 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (unsigned long v)
Definition at line 121 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (long long v)
Definition at line 126 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (unsigned long long v)
Definition at line 131 of file LogStream.cpp.
LogStream & adbase::LogStream::operator<< (const void * p)
Definition at line 136 of file LogStream.cpp.
References adbase::detail::convertHex().
self& adbase::LogStream::operator<< (float v) inline
Definition at line 123 of file LogStream.hpp.
References adbase::operator<<().
LogStream & adbase::LogStream::operator<< (double v)
Definition at line 149 of file LogStream.cpp.
self& adbase::LogStream::operator<< (char v) inline
Definition at line 129 of file LogStream.hpp.
References append().
self& adbase::LogStream::operator<< (const char * str) inline
Definition at line 134 of file LogStream.hpp.
References append().
self& adbase::LogStream::operator<< (const unsigned char * str) inline
Definition at line 144 of file LogStream.hpp.
self& adbase::LogStream::operator<< (const std::string & v) inline
Definition at line 148 of file LogStream.hpp.
References append().
self& adbase::LogStream::operator<< (const Buffer & v) inline
Definition at line 153 of file LogStream.hpp.
References adbase::detail::FixedBuffer< SIZE >::toString().
void adbase::LogStream::resetBuffer () inline
Definition at line 166 of file LogStream.hpp.
The documentation for this class was generated from the following files:
adbase/Logging/LogStream.hpp
adbase/Logging/LogStream.cpp