Adbase: adbase::mc::Interface Class Reference
adbase::mc::Interface Class Reference
#include <Interface.hpp>
Public Member Functions
Interface ()
~Interface ()
void setAddHandler (const AddHandler &addHandler)
void setAppendHandler (const AppendHandler &appendHandler)
void setDecrementHandler (const DecrementHandler &decrementHandler)
void setDeleteHandler (const DeleteHandler &deleteHandler)
void setFlushHandler (const FlushHandler &flushHandler)
void setGetHandler (const GetHandler &getHandler)
void setIncrementHandler (const IncrementHandler &incrementHandler)
void setPrependHandler (const PrependHandler &prependHandler)
void setNoopHandler (const NoopHandler &noopHandler)
void setQuitHandler (const QuitHandler &quitHandler)
void setReplaceHandler (const ReplaceHander &replaceHandler)
void setSetHandler (const SetHandler &setHandler)
void setVersionHandler (const VersionHandler &versionHandler)
void setVerbosityHandler (const VerbosityHandler &verbosityHandler)
void setStatHandler (const StatHandler &statHandler)
void setPreExecute (const PreExecute &preExecute)
void setPostExecute (const PostExecute &postExecute)
void setUnknownExecute (const UnknownExecute &unknownExecute)
const AddHandler & getAddHandler ()
const AppendHandler & getAppendHandler ()
const DecrementHandler & getDecrementHandler ()
const DeleteHandler & getDeleteHandler ()
const FlushHandler & getFlushHandler ()
const GetHandler & getGetHandler ()
const IncrementHandler & getIncrementHandler ()
const PrependHandler & getPrependHandler ()
const NoopHandler & getNoopHandler ()
const QuitHandler & getQuitHandler ()
const ReplaceHander & getReplaceHandler ()
const SetHandler & getSetHandler ()
const VersionHandler & getVersionHandler ()
const VerbosityHandler & getVerbosityHandler ()
const StatHandler & getStatHandler ()
const PreExecute & getPreExecute ()
const PostExecute & getPostExecute ()
const UnknownExecute & getUnknownExecute ()
Detailed Description
Definition at line 125 of file Interface.hpp.
Constructor & Destructor Documentation
adbase::mc::Interface::Interface ()
Definition at line 7 of file Interface.cpp.
adbase::mc::Interface::~Interface ()
Definition at line 14 of file Interface.cpp.
Member Function Documentation
const AddHandler & adbase::mc::Interface::getAddHandler ()
Definition at line 147 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const AppendHandler & adbase::mc::Interface::getAppendHandler ()
Definition at line 154 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const DecrementHandler & adbase::mc::Interface::getDecrementHandler ()
Definition at line 161 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const DeleteHandler & adbase::mc::Interface::getDeleteHandler ()
Definition at line 168 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const FlushHandler & adbase::mc::Interface::getFlushHandler ()
Definition at line 175 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const GetHandler & adbase::mc::Interface::getGetHandler ()
Definition at line 182 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const IncrementHandler & adbase::mc::Interface::getIncrementHandler ()
Definition at line 189 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const NoopHandler & adbase::mc::Interface::getNoopHandler ()
Definition at line 203 of file Interface.cpp.
Referenced by adbase::mc::Binary::processData().
const PostExecute & adbase::mc::Interface::getPostExecute ()
Definition at line 259 of file Interface.cpp.
const PreExecute & adbase::mc::Interface::getPreExecute ()
Definition at line 252 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData().
const PrependHandler & adbase::mc::Interface::getPrependHandler ()
Definition at line 196 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const QuitHandler & adbase::mc::Interface::getQuitHandler ()
Definition at line 210 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const ReplaceHander & adbase::mc::Interface::getReplaceHandler ()
Definition at line 217 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const SetHandler & adbase::mc::Interface::getSetHandler ()
Definition at line 224 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
const StatHandler & adbase::mc::Interface::getStatHandler ()
Definition at line 245 of file Interface.cpp.
Referenced by adbase::mc::Binary::processData().
const UnknownExecute & adbase::mc::Interface::getUnknownExecute ()
Definition at line 266 of file Interface.cpp.
const VerbosityHandler & adbase::mc::Interface::getVerbosityHandler ()
Definition at line 238 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData().
const VersionHandler & adbase::mc::Interface::getVersionHandler ()
Definition at line 231 of file Interface.cpp.
Referenced by adbase::mc::Ascii::processData(), and adbase::mc::Binary::processData().
void adbase::mc::Interface::setAddHandler (const AddHandler & addHandler)
Definition at line 21 of file Interface.cpp.
void adbase::mc::Interface::setAppendHandler (const AppendHandler & appendHandler)
Definition at line 28 of file Interface.cpp.
void adbase::mc::Interface::setDecrementHandler (const DecrementHandler & decrementHandler)
Definition at line 35 of file Interface.cpp.
void adbase::mc::Interface::setDeleteHandler (const DeleteHandler & deleteHandler)
Definition at line 42 of file Interface.cpp.
void adbase::mc::Interface::setFlushHandler (const FlushHandler & flushHandler)
Definition at line 49 of file Interface.cpp.
void adbase::mc::Interface::setGetHandler (const GetHandler & getHandler)
Definition at line 56 of file Interface.cpp.
void adbase::mc::Interface::setIncrementHandler (const IncrementHandler & incrementHandler)
Definition at line 63 of file Interface.cpp.
void adbase::mc::Interface::setNoopHandler (const NoopHandler & noopHandler)
Definition at line 77 of file Interface.cpp.
void adbase::mc::Interface::setPostExecute (const PostExecute & postExecute)
Definition at line 133 of file Interface.cpp.
void adbase::mc::Interface::setPreExecute (const PreExecute & preExecute)
Definition at line 126 of file Interface.cpp.
void adbase::mc::Interface::setPrependHandler (const PrependHandler & prependHandler)
Definition at line 70 of file Interface.cpp.
void adbase::mc::Interface::setQuitHandler (const QuitHandler & quitHandler)
Definition at line 84 of file Interface.cpp.
void adbase::mc::Interface::setReplaceHandler (const ReplaceHander & replaceHandler)
Definition at line 91 of file Interface.cpp.
void adbase::mc::Interface::setSetHandler (const SetHandler & setHandler)
Definition at line 98 of file Interface.cpp.
void adbase::mc::Interface::setStatHandler (const StatHandler & statHandler)
Definition at line 119 of file Interface.cpp.
void adbase::mc::Interface::setUnknownExecute (const UnknownExecute & unknownExecute)
Definition at line 140 of file Interface.cpp.
void adbase::mc::Interface::setVerbosityHandler (const VerbosityHandler & verbosityHandler)
Definition at line 112 of file Interface.cpp.
void adbase::mc::Interface::setVersionHandler (const VersionHandler & versionHandler)
Definition at line 105 of file Interface.cpp.
The documentation for this class was generated from the following files:
adbase/Mc/Interface.hpp
adbase/Mc/Interface.cpp