Adbase: adbase::TimerItem Class Reference
adbase::TimerItem Class Reference
adbase::Net
#include <Timer.hpp>
Public Member Functions
TimerItem (uint64_t timerId, EventBasePtr &base, int interval, const TimerCallback &cb, void *context, bool isEvery=false)
~TimerItem ()
void start ()
void stop ()
void timerHandler ()
void setDelTimerCallback (const DelTimerCallback &dc)
Detailed Description
Definition at line 22 of file Timer.hpp.
Constructor & Destructor Documentation
adbase::TimerItem::TimerItem (uint64_t timerId, EventBasePtr & base, int interval, const TimerCallback & cb, void * context, bool isEvery = false)
Definition at line 79 of file Timer.cpp.
References adbase::detail::timerHandler().
adbase::TimerItem::~TimerItem ()
Definition at line 96 of file Timer.cpp.
References LOG_DEBUG.
Member Function Documentation
void adbase::TimerItem::setDelTimerCallback (const DelTimerCallback & dc) inline
Definition at line 31 of file Timer.hpp.
void adbase::TimerItem::start ()
Definition at line 103 of file Timer.cpp.
void adbase::TimerItem::stop ()
Definition at line 110 of file Timer.cpp.
Referenced by timerHandler().
void adbase::TimerItem::timerHandler ()
Definition at line 119 of file Timer.cpp.
References stop().
Referenced by adbase::detail::timerHandler().
The documentation for this class was generated from the following files:
adbase/Net/Timer.hpp
adbase/Net/Timer.cpp