Adbase: adbase::mc::Context Class Reference
adbase::mc::Context Class Reference
#include <Context.hpp>
Public Member Functions
Context ()
~Context ()
void setAsciiBuffer (const char *data, size_t len)
const char * getAsciiBuffer (size_t &len)
int getAsciiBufferSize ()
void setAsciiCmd (AsciiCmd cmd)
AsciiCmd getAsciiCmd ()
Detailed Description
Definition at line 19 of file Context.hpp.
Constructor & Destructor Documentation
adbase::mc::Context::Context ()
Definition at line 8 of file Context.cpp.
adbase::mc::Context::~Context ()
Definition at line 14 of file Context.cpp.
Member Function Documentation
const char * adbase::mc::Context::getAsciiBuffer (size_t & len)
Definition at line 27 of file Context.cpp.
References adbase::Buffer::peek(), adbase::Buffer::readableBytes(), and adbase::Buffer::retrieve().
Referenced by adbase::mc::Ascii::processData().
int adbase::mc::Context::getAsciiBufferSize ()
Definition at line 36 of file Context.cpp.
References adbase::Buffer::readableBytes().
Referenced by adbase::mc::Ascii::processData().
AsciiCmd adbase::mc::Context::getAsciiCmd () inline
Definition at line 31 of file Context.hpp.
Referenced by adbase::mc::Ascii::processData().
void adbase::mc::Context::setAsciiBuffer (const char * data, size_t len)
Definition at line 20 of file Context.cpp.
References adbase::Buffer::append().
Referenced by adbase::mc::Ascii::processData().
void adbase::mc::Context::setAsciiCmd (AsciiCmd cmd) inline
Definition at line 27 of file Context.hpp.
Referenced by adbase::mc::Ascii::processData().
The documentation for this class was generated from the following files:
adbase/Mc/Context.hpp
adbase/Mc/Context.cpp