Adbase: adbase::mc::Handler Class Reference
adbase::mc::Handler Class Reference
#include <Handler.hpp>
Public Member Functions
Handler (Interface *interface)
~Handler ()
void onConnection (const TcpConnectionPtr &conn)
void onMessage (const TcpConnectionPtr &conn, evbuffer *evbuf, Timestamp reciveTime)
void onClose (const TcpConnectionPtr &conn)
Detailed Description
Definition at line 23 of file Handler.hpp.
Constructor & Destructor Documentation
adbase::mc::Handler::Handler (Interface * interface)
Definition at line 8 of file Handler.cpp.
adbase::mc::Handler::~Handler ()
Definition at line 15 of file Handler.cpp.
Member Function Documentation
void adbase::mc::Handler::onClose (const TcpConnectionPtr & conn)
Definition at line 53 of file Handler.cpp.
void adbase::mc::Handler::onConnection (const TcpConnectionPtr & conn)
Definition at line 21 of file Handler.cpp.
References LOG_TRACE.
void adbase::mc::Handler::onMessage (const TcpConnectionPtr & conn, evbuffer * evbuf, Timestamp reciveTime)
Definition at line 33 of file Handler.cpp.
References LOG_DEBUG, adbase::mc::Ascii::processData(), adbase::mc::Binary::processData(), adbase::mc::PROTOCOL_BINARY_REQ, and adbase::Timestamp::toString().
The documentation for this class was generated from the following files:
adbase/Mc/Handler.hpp
adbase/Mc/Handler.cpp