Adbase: adbase::mc::Ascii Class Reference
adbase::mc::Ascii Class Reference
#include <Ascii.hpp>
Public Member Functions
Ascii (Interface *interface)
~Ascii ()
void processData (const TcpConnectionPtr &conn, evbuffer *evbuf)
Detailed Description
Definition at line 43 of file Ascii.hpp.
Constructor & Destructor Documentation
adbase::mc::Ascii::Ascii (Interface * interface)
Definition at line 9 of file Ascii.cpp.
adbase::mc::Ascii::~Ascii ()
Definition at line 16 of file Ascii.cpp.
Member Function Documentation
void adbase::mc::Ascii::processData (const TcpConnectionPtr & conn, evbuffer * evbuf)
Definition at line 22 of file Ascii.cpp.
References adbase::mc::ADD_CMD, adbase::Buffer::append(), adbase::mc::APPEND_CMD, adbase::mc::CAS_CMD, adbase::mc::DECR_CMD, adbase::mc::DELETE_CMD, adbase::explode(), adbase::mc::FLUSH_ALL_CMD, adbase::mc::GET_CMD, adbase::mc::Interface::getAddHandler(), adbase::mc::Interface::getAppendHandler(), adbase::mc::Context::getAsciiBuffer(), adbase::mc::Context::getAsciiBufferSize(), adbase::mc::Context::getAsciiCmd(), adbase::mc::Interface::getDecrementHandler(), adbase::mc::Interface::getDeleteHandler(), adbase::mc::Interface::getFlushHandler(), adbase::mc::Interface::getGetHandler(), adbase::mc::Interface::getIncrementHandler(), adbase::mc::Interface::getPreExecute(), adbase::mc::Interface::getPrependHandler(), adbase::mc::Interface::getQuitHandler(), adbase::mc::Interface::getReplaceHandler(), adbase::mc::GETS_CMD, adbase::mc::Interface::getSetHandler(), adbase::mc::Interface::getVerbosityHandler(), adbase::mc::Interface::getVersionHandler(), adbase::mc::INCR_CMD, LOG_DEBUG, LOG_FATAL, adbase::Buffer::peek(), adbase::mc::PREPEND_CMD, adbase::mc::PROTOCOL_BINARY_RESPONSE_KEY_ENOENT, adbase::mc::PROTOCOL_BINARY_RESPONSE_SUCCESS, adbase::mc::QUIT_CMD, adbase::Buffer::readableBytes(), adbase::mc::REPLACE_CMD, adbase::Buffer::retrieve(), adbase::Buffer::retrieveAllAsString(), adbase::mc::SET_CMD, adbase::mc::Context::setAsciiBuffer(), adbase::mc::Context::setAsciiCmd(), adbase::mc::STATS_CMD, adbase::trim(), adbase::mc::UNKNOWN_CMD, adbase::mc::VERBOSITY_CMD, and adbase::mc::VERSION_CMD.
Referenced by adbase::mc::Handler::onMessage().
The documentation for this class was generated from the following files:
adbase/Mc/Ascii.hpp
adbase/Mc/Ascii.cpp