Adbase: adbase::mc::Binary Class Reference
adbase::mc::Binary Class Reference
#include <Binary.hpp>
Public Member Functions
Binary (Interface *interface)
~Binary ()
void processData (const TcpConnectionPtr &conn, evbuffer *evbuf)
Detailed Description
Definition at line 278 of file Binary.hpp.
Constructor & Destructor Documentation
adbase::mc::Binary::Binary (Interface * interface)
Definition at line 9 of file Binary.cpp.
adbase::mc::Binary::~Binary ()
Definition at line 16 of file Binary.cpp.
Member Function Documentation
void adbase::mc::Binary::processData (const TcpConnectionPtr & conn, evbuffer * evbuf)
Definition at line 22 of file Binary.cpp.
References adbase::mc::ProtocolBinaryResponseGet::body, adbase::mc::ProtocolBinaryResponseIncr::body, adbase::mc::ProtocolBinaryRequestHeader::bodylen, adbase::mc::ProtocolBinaryResponseHeader::bodylen, adbase::mc::ProtocolBinaryResponseNoExtras::bytes, adbase::mc::ProtocolBinaryResponseGet::bytes, adbase::mc::ProtocolBinaryResponseIncr::bytes, adbase::mc::ProtocolBinaryRequestHeader::cas, adbase::mc::ProtocolBinaryResponseHeader::cas, adbase::mc::ProtocolBinaryRequestIncrExtras::delta, adbase::mc::ProtocolBinaryRequestSetExtras::expiration, adbase::mc::ProtocolBinaryRequestIncrExtras::expiration, adbase::mc::ProtocolBinaryRequestFlushExtras::expiration, adbase::mc::ProtocolBinaryResponseHeader::extlen, adbase::mc::ProtocolBinaryRequestSetExtras::flags, adbase::mc::Interface::getAddHandler(), adbase::mc::Interface::getAppendHandler(), adbase::mc::Interface::getDecrementHandler(), adbase::mc::Interface::getDeleteHandler(), adbase::mc::Interface::getFlushHandler(), adbase::mc::Interface::getGetHandler(), adbase::mc::Interface::getIncrementHandler(), adbase::mc::Interface::getNoopHandler(), adbase::mc::Interface::getPrependHandler(), adbase::mc::Interface::getQuitHandler(), adbase::mc::Interface::getReplaceHandler(), adbase::mc::Interface::getSetHandler(), adbase::mc::Interface::getStatHandler(), adbase::mc::Interface::getVersionHandler(), adbase::mc::ProtocolBinaryResponseNoExtras::header, adbase::mc::ProtocolBinaryResponseGet::header, adbase::mc::ProtocolBinaryResponseIncr::header, adbase::hostToNetwork16(), adbase::hostToNetwork32(), adbase::hostToNetwork64(), adbase::mc::ProtocolBinaryRequestIncrExtras::initial, adbase::mc::ProtocolBinaryRequestHeader::keylen, adbase::mc::ProtocolBinaryResponseHeader::keylen, LOG_DEBUG, LOG_ERROR, LOG_TRACE, adbase::mc::ProtocolBinaryResponseHeader::magic, adbase::mc::ProtocolBinaryResponseNoExtras::message, adbase::mc::ProtocolBinaryResponseGet::message, adbase::mc::ProtocolBinaryResponseIncr::message, adbase::networkToHost16(), adbase::networkToHost32(), adbase::networkToHost64(), adbase::mc::ProtocolBinaryRequestHeader::opaque, adbase::mc::ProtocolBinaryResponseHeader::opaque, adbase::mc::ProtocolBinaryRequestHeader::opcode, adbase::mc::ProtocolBinaryResponseHeader::opcode, adbase::Buffer::peek(), adbase::mc::PROTOCOL_BINARY_CMD_ADD, adbase::mc::PROTOCOL_BINARY_CMD_ADDQ, adbase::mc::PROTOCOL_BINARY_CMD_APPEND, adbase::mc::PROTOCOL_BINARY_CMD_APPENDQ, adbase::mc::PROTOCOL_BINARY_CMD_DECREMENT, adbase::mc::PROTOCOL_BINARY_CMD_DECREMENTQ, adbase::mc::PROTOCOL_BINARY_CMD_DEL_VBUCKET, adbase::mc::PROTOCOL_BINARY_CMD_DELETE, adbase::mc::PROTOCOL_BINARY_CMD_DELETEQ, adbase::mc::PROTOCOL_BINARY_CMD_FLUSH, adbase::mc::PROTOCOL_BINARY_CMD_FLUSHQ, adbase::mc::PROTOCOL_BINARY_CMD_GAT, adbase::mc::PROTOCOL_BINARY_CMD_GATK, adbase::mc::PROTOCOL_BINARY_CMD_GATKQ, adbase::mc::PROTOCOL_BINARY_CMD_GATQ, adbase::mc::PROTOCOL_BINARY_CMD_GET, adbase::mc::PROTOCOL_BINARY_CMD_GET_VBUCKET, adbase::mc::PROTOCOL_BINARY_CMD_GETK, adbase::mc::PROTOCOL_BINARY_CMD_GETKQ, adbase::mc::PROTOCOL_BINARY_CMD_GETQ, adbase::mc::PROTOCOL_BINARY_CMD_INCREMENT, adbase::mc::PROTOCOL_BINARY_CMD_INCREMENTQ, adbase::mc::PROTOCOL_BINARY_CMD_LAST_RESERVED, adbase::mc::PROTOCOL_BINARY_CMD_NOOP, adbase::mc::PROTOCOL_BINARY_CMD_PREPEND, adbase::mc::PROTOCOL_BINARY_CMD_PREPENDQ, adbase::mc::PROTOCOL_BINARY_CMD_QUIT, adbase::mc::PROTOCOL_BINARY_CMD_QUITQ, adbase::mc::PROTOCOL_BINARY_CMD_RAPPEND, adbase::mc::PROTOCOL_BINARY_CMD_RAPPENDQ, adbase::mc::PROTOCOL_BINARY_CMD_RDECR, adbase::mc::PROTOCOL_BINARY_CMD_RDECRQ, adbase::mc::PROTOCOL_BINARY_CMD_RDELETE, adbase::mc::PROTOCOL_BINARY_CMD_RDELETEQ, adbase::mc::PROTOCOL_BINARY_CMD_REPLACE, adbase::mc::PROTOCOL_BINARY_CMD_REPLACEQ, adbase::mc::PROTOCOL_BINARY_CMD_RGET, adbase::mc::PROTOCOL_BINARY_CMD_RINCR, adbase::mc::PROTOCOL_BINARY_CMD_RINCRQ, adbase::mc::PROTOCOL_BINARY_CMD_RPREPEND, adbase::mc::PROTOCOL_BINARY_CMD_RPREPENDQ, adbase::mc::PROTOCOL_BINARY_CMD_RSET, adbase::mc::PROTOCOL_BINARY_CMD_RSETQ, adbase::mc::PROTOCOL_BINARY_CMD_SASL_AUTH, adbase::mc::PROTOCOL_BINARY_CMD_SASL_LIST_MECHS, adbase::mc::PROTOCOL_BINARY_CMD_SASL_STEP, adbase::mc::PROTOCOL_BINARY_CMD_SCRUB, adbase::mc::PROTOCOL_BINARY_CMD_SET, adbase::mc::PROTOCOL_BINARY_CMD_SET_VBUCKET, adbase::mc::PROTOCOL_BINARY_CMD_SETQ, adbase::mc::PROTOCOL_BINARY_CMD_STAT, adbase::mc::PROTOCOL_BINARY_CMD_TAP_CHECKPOINT_END, adbase::mc::PROTOCOL_BINARY_CMD_TAP_CHECKPOINT_START, adbase::mc::PROTOCOL_BINARY_CMD_TAP_CONNECT, adbase::mc::PROTOCOL_BINARY_CMD_TAP_DELETE, adbase::mc::PROTOCOL_BINARY_CMD_TAP_FLUSH, adbase::mc::PROTOCOL_BINARY_CMD_TAP_MUTATION, adbase::mc::PROTOCOL_BINARY_CMD_TAP_OPAQUE, adbase::mc::PROTOCOL_BINARY_CMD_TAP_VBUCKET_SET, adbase::mc::PROTOCOL_BINARY_CMD_TOUCH, adbase::mc::PROTOCOL_BINARY_CMD_VERBOSITY, adbase::mc::PROTOCOL_BINARY_CMD_VERSION, adbase::mc::PROTOCOL_BINARY_RES, adbase::mc::PROTOCOL_BINARY_RESPONSE_NOT_SUPPORTED, adbase::mc::PROTOCOL_BINARY_RESPONSE_SUCCESS, adbase::mc::PROTOCOL_BINARY_RESPONSE_UNKNOWN_COMMAND, adbase::Buffer::readableBytes(), adbase::mc::ProtocolBinaryRequestHeader::request, adbase::mc::ProtocolBinaryResponseHeader::response, adbase::Buffer::retrieveAll(), and adbase::mc::ProtocolBinaryResponseHeader::status.
Referenced by adbase::mc::Handler::onMessage().
The documentation for this class was generated from the following files:
adbase/Mc/Binary.hpp
adbase/Mc/Binary.cpp