Adbase: adbase::TcpClient Class Reference
adbase::TcpClient Class Reference
adbase::Net
#include <TcpClient.hpp>
Public Member Functions
TcpClient (EventBasePtr &base, const InetAddress &serverAddr, const std::string &name, Timer *timer)
TcpClient (EventBasePtr &base, const std::string &hostname, int port, const std::string &name, Timer *timer)
~TcpClient ()
void connect ()
void disconnect ()
void stop ()
TcpConnectionPtr connection () const
EventBasePtr & getLoop () const
bool retry () const
void enableRetry ()
const std::string & name () const
void setConnectionCallback (const ConnectionCallback &cb)
void setMessageCallback (const MessageCallback &cb)
void setWriteCompleteCallback (const WriteCompleteCallback &cb)
Detailed Description
Definition at line 21 of file TcpClient.hpp.
Constructor & Destructor Documentation
adbase::TcpClient::TcpClient (EventBasePtr & base, const InetAddress & serverAddr, const std::string & name, Timer * timer)
Definition at line 7 of file TcpClient.cpp.
References LOG_INFO.
adbase::TcpClient::TcpClient (EventBasePtr & base, const std::string & hostname, int port, const std::string & name, Timer * timer)
Definition at line 24 of file TcpClient.cpp.
References LOG_INFO.
adbase::TcpClient::~TcpClient ()
Definition at line 41 of file TcpClient.cpp.
References LOG_INFO.
Member Function Documentation
void adbase::TcpClient::connect ()
Definition at line 49 of file TcpClient.cpp.
References LOG_INFO.
Referenced by adbase::mc::ClientHandler::start().
TcpConnectionPtr adbase::TcpClient::connection () const inline
Definition at line 31 of file TcpClient.hpp.
void adbase::TcpClient::disconnect ()
Definition at line 59 of file TcpClient.cpp.
void adbase::TcpClient::enableRetry () inline
Definition at line 44 of file TcpClient.hpp.
Referenced by adbase::mc::ClientHandler::start().
EventBasePtr& adbase::TcpClient::getLoop () const inline
Definition at line 36 of file TcpClient.hpp.
const std::string& adbase::TcpClient::name () const inline
Definition at line 48 of file TcpClient.hpp.
bool adbase::TcpClient::retry () const inline
Definition at line 40 of file TcpClient.hpp.
void adbase::TcpClient::setConnectionCallback (const ConnectionCallback & cb) inline
Definition at line 52 of file TcpClient.hpp.
Referenced by adbase::mc::ClientHandler::start().
void adbase::TcpClient::setMessageCallback (const MessageCallback & cb) inline
Definition at line 55 of file TcpClient.hpp.
Referenced by adbase::mc::ClientHandler::start().
void adbase::TcpClient::setWriteCompleteCallback (const WriteCompleteCallback & cb) inline
Definition at line 58 of file TcpClient.hpp.
void adbase::TcpClient::stop ()
Definition at line 72 of file TcpClient.cpp.
References adbase::sockets::getLocalAddr(), adbase::sockets::getPeerAddr(), and LOG_INFO.
Referenced by adbase::mc::ClientHandler::stop().
The documentation for this class was generated from the following files:
adbase/Net/TcpClient.hpp
adbase/Net/TcpClient.cpp