Adbase: adbase::Logger Class Reference
adbase::Logger Class Reference
adbase::Logging
#include <Logging.hpp>
Classes
class SourceFile
Public Types
enum LogLevel {
TRACE, DEBUG, INFO, WARN,
ERROR, FATAL, NUM_LOG_LEVELS
}
typedef std::function< void(const char *msg, size_t len)> OutputFunc
typedef std::function< void()> FlushFunc
Public Member Functions
Logger (SourceFile file, int line)
Logger (SourceFile file, int line, LogLevel level)
Logger (SourceFile file, int line, LogLevel level, const char *func)
Logger (SourceFile file, int line, bool toAbort)
~Logger ()
LogStream & stream ()
Static Public Member Functions
static LogLevel logLevel ()
static void setLogLevel (LogLevel level)
static void setOutput (const OutputFunc &func)
static void setFlush (const FlushFunc &func)
static void setTimeZone (const TimeZone &tz)
Detailed Description
Definition at line 20 of file Logging.hpp.
Member Typedef Documentation
typedef std::function<void ()> adbase::Logger::FlushFunc
Definition at line 76 of file Logging.hpp.
typedef std::function<void (const char* msg, size_t len)> adbase::Logger::OutputFunc
Definition at line 75 of file Logging.hpp.
Member Enumeration Documentation
enum adbase::Logger::LogLevel
Enumerator
TRACE
DEBUG
INFO
WARN
ERROR
FATAL
NUM_LOG_LEVELS
Definition at line 22 of file Logging.hpp.
Constructor & Destructor Documentation
adbase::Logger::Logger (SourceFile file, int line)
Definition at line 127 of file Logging.cpp.
Referenced by adbase::CheckNotNull().
adbase::Logger::Logger (SourceFile file, int line, LogLevel level)
Definition at line 136 of file Logging.cpp.
adbase::Logger::Logger (SourceFile file, int line, LogLevel level, const char * func)
Definition at line 131 of file Logging.cpp.
adbase::Logger::Logger (SourceFile file, int line, bool toAbort)
Definition at line 140 of file Logging.cpp.
adbase::Logger::~Logger ()
Definition at line 144 of file Logging.cpp.
References adbase::detail::FixedBuffer< SIZE >::data(), FATAL, adbase::gFlush, adbase::gOutput, adbase::detail::FixedBuffer< SIZE >::length(), and stream().
Member Function Documentation
void adbase::Logger::setFlush (const FlushFunc & func) static
Definition at line 162 of file Logging.cpp.
void adbase::Logger::setLogLevel (Logger::LogLevel level) static
Definition at line 154 of file Logging.cpp.
Referenced by stream().
void adbase::Logger::setOutput (const OutputFunc & func) static
Definition at line 158 of file Logging.cpp.
void adbase::Logger::setTimeZone (const TimeZone & tz) static
Definition at line 166 of file Logging.cpp.
LogStream& adbase::Logger::stream () inline
Definition at line 68 of file Logging.hpp.
References logLevel(), and setLogLevel().
Referenced by ~Logger().
The documentation for this class was generated from the following files:
adbase/Logging/Logging.hpp
adbase/Logging/Logging.cpp