Adbase: adbase::kafka::Producer Class Reference
adbase::kafka::Producer Class Reference
#include <Producer.hpp>
Public Member Functions
Producer (const std::string &brokerList, int queueLen, const std::string &debug)
~Producer ()
void start ()
void stop ()
void threadFunc (void *data)
void deliveredCallback (rd_kafka_resp_err_t err, uint64_t ackCode)
void setSendHandler (const MessageSendCallback &sendHandler)
void setErrorHandler (const MessageErrorCallback &errorHandler)
void setAckHandler (const MessageAckCallback &ackHandler)
Static Public Member Functions
static void deleteThread (std::thread *t)
static void logger (const rd_kafka_t *rk, int level, const char *fac, const char *buf)
Detailed Description
Definition at line 37 of file Producer.hpp.
Constructor & Destructor Documentation
adbase::kafka::Producer::Producer (const std::string & brokerList, int queueLen, const std::string & debug)
Definition at line 23 of file Producer.cpp.
adbase::kafka::Producer::~Producer ()
Definition at line 32 of file Producer.cpp.
Member Function Documentation
void adbase::kafka::Producer::deleteThread (std::thread * t) static
Definition at line 211 of file Producer.cpp.
Referenced by start().
void adbase::kafka::Producer::deliveredCallback (rd_kafka_resp_err_t err, uint64_t ackCode)
Definition at line 156 of file Producer.cpp.
References adbase::kafka::detail::deliveredCallback(), LOG_ERROR, LOG_TRACE, and logger().
Referenced by adbase::kafka::detail::deliveredCallback().
void adbase::kafka::Producer::logger (const rd_kafka_t * rk, int level, const char * fac, const char * buf) static
Definition at line 219 of file Producer.cpp.
Referenced by deliveredCallback().
void adbase::kafka::Producer::setAckHandler (const MessageAckCallback & ackHandler) inline
Definition at line 56 of file Producer.hpp.
void adbase::kafka::Producer::setErrorHandler (const MessageErrorCallback & errorHandler) inline
Definition at line 52 of file Producer.hpp.
void adbase::kafka::Producer::setSendHandler (const MessageSendCallback & sendHandler) inline
Definition at line 48 of file Producer.hpp.
void adbase::kafka::Producer::start ()
Definition at line 38 of file Producer.cpp.
References deleteThread(), and threadFunc().
void adbase::kafka::Producer::stop ()
Definition at line 50 of file Producer.cpp.
References LOG_ERROR, and LOG_INFO.
void adbase::kafka::Producer::threadFunc (void * data)
Definition at line 63 of file Producer.cpp.
References adbase::kafka::KafkaContext::ackCode, adbase::kafka::KafkaContext::context, LOG_ERROR, LOG_INFO, LOG_TRACE, adbase::Buffer::peek(), and adbase::Buffer::readableBytes().
Referenced by start().
The documentation for this class was generated from the following files:
adbase/Kafka/Producer.hpp
adbase/Kafka/Producer.cpp