Adbase: adbase::http::Config Class Reference
adbase::http::Config Class Reference
#include <Config.hpp>
Public Member Functions
Config (std::string address="127.0.0.1", int port=10000, int timeout=30)
Config (const Config &config)
const std::string & getBindAddress () const
int getBindPort () const
int getTimeout () const
int getStatInterval () const
const TimeZone & getTimeZone ()
const std::string & getLogFormat () const
const std::string & getServerName () const
const std::string & getLogDir () const
int getLogRollSize () const
void setBindAddress (std::string address)
void setLogFormat (std::string logFormat)
void setTimeZone (TimeZone &zone)
void setBindPort (int port)
void setTimeout (int timout)
void setLogRollSize (int size)
void setStatInterval (int interval)
void setLogDir (const std::string dir)
void setServerName (const std::string name)
virtual ~Config ()
Friends
std::ostream & operator<< (std::ostream &os, const Config &config)
Detailed Description
Definition at line 21 of file Config.hpp.
Constructor & Destructor Documentation
adbase::http::Config::Config (std::string address = "127.0.0.1", int port = 10000, int timeout = 30)
Definition at line 9 of file Config.cpp.
adbase::http::Config::Config (const Config & config)
Definition at line 18 of file Config.cpp.
virtual adbase::http::Config::~Config () inline virtual
Definition at line 46 of file Config.hpp.
Member Function Documentation
const std::string& adbase::http::Config::getBindAddress () const inline
Definition at line 25 of file Config.hpp.
Referenced by adbase::http::Server::threadFunc().
int adbase::http::Config::getBindPort () const inline
Definition at line 26 of file Config.hpp.
Referenced by adbase::http::Server::threadFunc().
const std::string& adbase::http::Config::getLogDir () const inline
Definition at line 32 of file Config.hpp.
Referenced by adbase::http::Server::start().
const std::string& adbase::http::Config::getLogFormat () const inline
Definition at line 30 of file Config.hpp.
Referenced by adbase::http::Server::setLocationFallback().
int adbase::http::Config::getLogRollSize () const inline
Definition at line 33 of file Config.hpp.
References operator<<, setBindAddress(), setBindPort(), setLogDir(), setLogFormat(), setLogRollSize(), setServerName(), setStatInterval(), setTimeout(), and setTimeZone().
Referenced by adbase::http::Server::start().
const std::string& adbase::http::Config::getServerName () const inline
Definition at line 31 of file Config.hpp.
Referenced by adbase::http::Server::start().
int adbase::http::Config::getStatInterval () const inline
Definition at line 28 of file Config.hpp.
Referenced by adbase::http::Server::Server().
int adbase::http::Config::getTimeout () const inline
Definition at line 27 of file Config.hpp.
const TimeZone& adbase::http::Config::getTimeZone () inline
Definition at line 29 of file Config.hpp.
Referenced by adbase::http::Server::Server().
void adbase::http::Config::setBindAddress (std::string address)
Definition at line 32 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setBindPort (int port)
Definition at line 46 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setLogDir (const std::string dir)
Definition at line 74 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setLogFormat (std::string logFormat)
Definition at line 39 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setLogRollSize (int size)
Definition at line 88 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setServerName (const std::string name)
Definition at line 81 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setStatInterval (int interval)
Definition at line 60 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setTimeout (int timout)
Definition at line 53 of file Config.cpp.
Referenced by getLogRollSize().
void adbase::http::Config::setTimeZone (TimeZone & zone)
Definition at line 67 of file Config.cpp.
Referenced by getLogRollSize().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Config & config) friend
Definition at line 95 of file Config.cpp.
Referenced by getLogRollSize().
The documentation for this class was generated from the following files:
adbase/Http/Config.hpp
adbase/Http/Config.cpp